# Generated by Django 5.2.17 on 2026-08-21 10:11

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.design_orders.models
import apps.design_orders.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name_plural": "design categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DesignOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_number",
                    models.CharField(
                        default=apps.design_orders.models.generate_order_number,
                        editable=False,
                        max_length=22,
                        unique=True,
                    ),
                ),
                ("design_name", models.CharField(max_length=200)),
                ("design_description", models.TextField(blank=True)),
                (
                    "customer_reference_image",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.design_orders.models.reference_image_path,
                        validators=[apps.design_orders.validators.validate_reference_image],
                    ),
                ),
                (
                    "design_preview_image",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.design_orders.models.preview_image_path,
                        validators=[apps.design_orders.validators.validate_preview_image],
                    ),
                ),
                (
                    "design_file_reference",
                    models.FileField(
                        blank=True,
                        upload_to=apps.design_orders.models.design_file_path,
                        validators=[apps.design_orders.validators.validate_design_file],
                    ),
                ),
                ("design_file_name", models.CharField(blank=True, max_length=255)),
                ("design_file_type", models.CharField(blank=True, max_length=20)),
                (
                    "cut_quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=14),
                ),
                (
                    "order_date",
                    models.DateField(db_index=True, default=django.utils.timezone.localdate),
                ),
                ("expected_delivery_date", models.DateField(db_index=True)),
                ("actual_delivery_date", models.DateField(blank=True, db_index=True, null=True)),
                ("payment_due_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("DESIGN_PREPARATION", "Design preparation"),
                            ("CUTTING", "Cutting"),
                            ("READY_FOR_DELIVERY", "Ready for delivery"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="NEW",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_design_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="design_orders",
                        to="customers.customer",
                    ),
                ),
                (
                    "design_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="design_orders",
                        to="design_orders.designcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignOrderStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEW", "New"),
                            ("DESIGN_PREPARATION", "Design preparation"),
                            ("CUTTING", "Cutting"),
                            ("READY_FOR_DELIVERY", "Ready for delivery"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("DESIGN_PREPARATION", "Design preparation"),
                            ("CUTTING", "Cutting"),
                            ("READY_FOR_DELIVERY", "Ready for delivery"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=30,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="design_order_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "design_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="design_orders.designorder",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="designorder",
            index=models.Index(
                fields=["status", "order_date"], name="design_order_status_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="designorder",
            index=models.Index(
                fields=["customer", "-created_at"], name="design_order_customer_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="designorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("cut_quantity__gt", 0)), name="design_order_quantity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="designorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gt", 0)), name="design_order_price_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="designorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gt", 0)), name="design_order_total_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="designorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("expected_delivery_date__gte", models.F("order_date"))),
                name="design_order_delivery_after_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="designorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("actual_delivery_date__isnull", False), ("status", "DELIVERED")),
                    models.Q(
                        models.Q(("status", "DELIVERED"), _negated=True),
                        ("actual_delivery_date__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="design_order_actual_date_matches_status",
            ),
        ),
        migrations.AddIndex(
            model_name="designorderstatushistory",
            index=models.Index(
                fields=["design_order", "created_at"], name="order_history_date_idx"
            ),
        ),
    ]
