# Generated by Django 5.2.17 on 2026-08-25 19:41

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("design_orders", "0012_designorderpayment_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="designorder",
            name="material_quantity",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="designorder",
            name="material_total_cost",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), editable=False, max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="designorder",
            name="material_unit_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
