# Generated by Django 5.2.17 on 2026-08-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_orders', '0013_designorder_material_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designorder',
            name='material_total_cost',
        ),
        migrations.RemoveField(
            model_name='designorder',
            name='material_unit_cost',
        ),
    ]
