# Generated by Django 5.2.17 on 2026-08-25 22:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerLedgerEntry",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False, default=None, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entry_type", models.CharField(choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")], max_length=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("source_type", models.CharField(blank=True, max_length=50)),
                ("source_id", models.CharField(blank=True, max_length=100)),
                ("posted_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="customers.customer")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="customer_ledger_entries", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-posted_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["customer", "posted_at"], name="ledger_customer_posted_idx"),
                    models.Index(fields=["source_type", "source_id"], name="ledger_source_idx"),
                ],
            },
        ),
    ]
