import { Check, KeyRound, Plus, Search, ShieldCheck, UserCheck, UserCog, UserX, X } from "lucide-react";
import { useMemo, useState } from "react";
import { PageHeader, StatePanel } from "@/components/ui/Page";
import { ApiError } from "@/lib/api-client";
import type { User, UserRole } from "@/types/api";
import { useAuth } from "@/features/auth/auth-context";
import { useUserMutations, useUsers } from "./hooks";

const roles: { value: UserRole; label: string; detail: string; permissions: string[] }[] = [
  { value: "OWNER", label: "مالک", detail: "ټول سیسټم ته بشپړ لاسرسی", permissions: ["کاروونکي", "مالي حساب", "فرمایشونه", "راپورونه", "Backup"] },
  { value: "MANAGER", label: "مدیر", detail: "د ورځنیو او مالي چارو مدیریت", permissions: ["مشتریان", "فرمایشونه", "تادیات", "لګښتونه", "راپورونه"] },
  { value: "OPERATOR", label: "کارکوونکی", detail: "یوازې مشتریان او فرمایشونه", permissions: ["مشتریان", "فرمایشونه"] },
  { value: "VIEWER", label: "کتونکی", detail: "یوازې راپورونه لیدلی شي", permissions: ["راپورونه"] },
];
const field = "mt-1.5 h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-100";
const emptyForm = { full_name: "", email: "", phone: "", role: "OPERATOR" as UserRole, password: "" };

export function UsersPage() {
  const users = useUsers(); const mutations = useUserMutations(); const { user: currentUser } = useAuth();
  const [search, setSearch] = useState(""); const [formOpen, setFormOpen] = useState(false); const [form, setForm] = useState(emptyForm); const [editing, setEditing] = useState<User | null>(null); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const visible = useMemo(() => (users.data?.data ?? []).filter((item) => `${item.full_name} ${item.email} ${item.phone}`.toLowerCase().includes(search.toLowerCase())), [users.data, search]);
  const openCreate = () => { setEditing(null); setForm(emptyForm); setError(""); setFormOpen(true); };
  const openEdit = (item: User) => { setEditing(item); setForm({ full_name: item.full_name, email: item.email, phone: item.phone, role: item.role, password: "" }); setError(""); setFormOpen(true); };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(""); setSuccess(""); try { if (editing) await mutations.update.mutateAsync({ id: editing.id, input: { full_name: form.full_name, email: form.email, phone: form.phone, role: form.role } }); else await mutations.create.mutateAsync(form); setFormOpen(false); setSuccess(editing ? "د کاروونکي معلومات تازه شول." : "نوی کاروونکی جوړ شو."); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "معلومات ثبت نه شول."); } };
  const changePassword = async (item: User) => { const password = window.prompt(`د ${item.full_name} لپاره نوی قوي Password ولیکئ:`); if (!password) return; try { await mutations.password.mutateAsync({ id: item.id, password }); setSuccess("Password په بریالیتوب بدل شو."); setError(""); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Password بدل نه شو."); } };
  const toggleActive = async (item: User) => { if (!window.confirm(`${item.full_name} ${item.is_active ? "غیرفعال" : "فعال"} شي؟`)) return; try { await mutations.active.mutateAsync({ id: item.id, active: !item.is_active }); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "حالت بدل نه شو."); } };

  if (users.isLoading) return <StatePanel title="کاروونکي راخیستل کېږي…" />;
  if (users.isError) return <StatePanel title="کاروونکي را نه غلل" detail="له سرور سره اړیکه وګورئ." className="border-red-200 bg-red-50" />;
  return <section dir="rtl" className="text-right">
    <PageHeader eyebrow="امنیت او لاسرسی" title="د کاروونکو مدیریت" description="کاروونکي، Role، صلاحیتونه او Password له یوه ځایه اداره کړئ." actions={<button onClick={openCreate} className="inline-flex h-11 items-center gap-2 rounded-xl bg-blue-600 px-5 text-sm font-black text-white shadow-md hover:bg-blue-700"><Plus className="size-4" /> نوی کاروونکی</button>} />
    {(error || success) && <div className={`mb-5 flex items-center gap-2 rounded-xl border px-4 py-3 text-sm font-bold ${error ? "border-red-200 bg-red-50 text-red-700" : "border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{error ? <X className="size-4" /> : <Check className="size-4" />}{error || success}</div>}
    <div className="mb-5 grid gap-3 md:grid-cols-4">{roles.map((role) => <article key={role.value} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-blue-50 text-blue-600"><ShieldCheck className="size-5" /></span><div><h2 className="font-black">{role.label}</h2><p className="text-[11px] text-slate-500">{role.detail}</p></div></div><div className="mt-3 flex flex-wrap gap-1">{role.permissions.map((p) => <span key={p} className="rounded-md bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-600">{p}</span>)}</div></article>)}</div>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b bg-slate-50/70 px-5 py-4"><div><h2 className="font-black">ثبت شوي کاروونکي</h2><p className="mt-1 text-xs text-slate-500">ټول: {users.data?.meta.count ?? 0}</p></div><label className="relative w-full sm:w-72"><Search className="absolute right-3 top-3 size-4 text-slate-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="نوم، Email یا شمېره" className="h-10 w-full rounded-xl border border-slate-200 pr-9 pl-3 text-sm outline-none focus:border-blue-500" /></label></div><div className="divide-y">{visible.map((item) => { const role = roles.find((r) => r.value === item.role)!; return <div key={item.id} className="flex flex-wrap items-center justify-between gap-4 px-5 py-4 hover:bg-slate-50"><div className="flex items-center gap-3"><span className={`grid size-11 place-items-center rounded-xl ${item.is_active ? "bg-emerald-50 text-emerald-600" : "bg-slate-100 text-slate-400"}`}><UserCog className="size-5" /></span><div><div className="flex items-center gap-2"><strong>{item.full_name}</strong>{item.id === currentUser?.id && <span className="rounded-full bg-blue-50 px-2 py-0.5 text-[10px] font-bold text-blue-700">ستاسو حساب</span>}</div><p dir="ltr" className="mt-1 text-right text-xs text-slate-500">{item.email}{item.phone ? ` · ${item.phone}` : ""}</p></div></div><div className="flex flex-wrap items-center gap-2"><span className="rounded-lg bg-blue-50 px-3 py-2 text-xs font-black text-blue-700">{role.label}</span><span className={`rounded-lg px-3 py-2 text-xs font-bold ${item.is_active ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>{item.is_active ? "فعال" : "غیرفعال"}</span><button onClick={() => openEdit(item)} className="rounded-lg border px-3 py-2 text-xs font-bold hover:bg-slate-50">اصلاح</button><button onClick={() => void changePassword(item)} className="inline-flex items-center gap-1 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs font-bold text-amber-700"><KeyRound className="size-3.5" /> Password</button>{item.id !== currentUser?.id && <button onClick={() => void toggleActive(item)} className={`rounded-lg p-2 ${item.is_active ? "bg-red-50 text-red-600" : "bg-emerald-50 text-emerald-600"}`} title={item.is_active ? "غیرفعالول" : "فعالول"}>{item.is_active ? <UserX className="size-4" /> : <UserCheck className="size-4" />}</button>}</div></div>; })}</div></section>
    {formOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4 backdrop-blur-sm" onMouseDown={() => setFormOpen(false)}><form onSubmit={submit} onMouseDown={(e) => e.stopPropagation()} className="w-full max-w-2xl rounded-3xl bg-white p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-xl font-black">{editing ? "کاروونکی اصلاح کول" : "نوی کاروونکی"}</h2><p className="mt-1 text-xs text-slate-500">Role د کاروونکي لاسرسی په اتومات ډول ټاکي.</p></div><button type="button" onClick={() => setFormOpen(false)} className="rounded-xl bg-slate-100 p-2"><X className="size-5" /></button></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">بشپړ نوم<input required value={form.full_name} onChange={(e) => setForm({...form, full_name:e.target.value})} className={field} /></label><label className="text-sm font-bold">Email / Username<input required type="email" dir="ltr" value={form.email} onChange={(e) => setForm({...form, email:e.target.value})} className={`${field} text-left`} /></label><label className="text-sm font-bold">د اړیکې شمېره<input dir="ltr" value={form.phone} onChange={(e) => setForm({...form, phone:e.target.value})} className={`${field} text-left`} /></label><label className="text-sm font-bold">Role<select value={form.role} onChange={(e) => setForm({...form, role:e.target.value as UserRole})} className={field}>{roles.map((r) => <option key={r.value} value={r.value}>{r.label} — {r.detail}</option>)}</select></label>{!editing && <label className="text-sm font-bold sm:col-span-2">لومړنی Password<input required minLength={8} type="password" value={form.password} onChange={(e) => setForm({...form, password:e.target.value})} className={field} /></label>}</div><button disabled={mutations.create.isPending || mutations.update.isPending} className="mt-6 h-11 w-full rounded-xl bg-blue-600 font-black text-white hover:bg-blue-700">{editing ? "بدلونونه ساتل" : "کاروونکی جوړول"}</button></form></div>}
  </section>;
}

export default UsersPage;
