# Generated by Django 5.2.17 on 2026-08-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daily_journal", "0003_payableaccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("ELECTRICITY_WATER", "Electricity and water"),
                    ("RENT", "Rent"),
                    ("FOOD_STAFF", "Food and daily staff expenses"),
                    ("TRANSPORTATION", "Transportation"),
                    ("MAINTENANCE", "Maintenance"),
                    ("MATERIALS", "Materials"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
