# Generated by Django 5.2.17 on 2026-08-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_journal', '0007_repayment_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ELECTRICITY_WATER', 'برېښنا او اوبه'), ('RENT', 'کرایه'), ('FOOD_STAFF', 'خوراک او د کارکوونکو ورځني لګښتونه'), ('TRANSPORTATION', 'ترانسپورټ'), ('MAINTENANCE', 'ساتنه او ترمیم'), ('MATERIALS', 'مواد'), ('OTHER', 'نور لګښتونه')], max_length=30),
        ),
    ]
