# Generated by Django 5.2.17 on 2026-09-03 13:11

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daily_journal", "0011_payableaccount_origin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyclosing",
            name="money_received",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
        ),
        migrations.CreateModel(
            name="CashReconciliation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reconciliation_date", models.DateField(db_index=True)),
                ("system_balance", models.DecimalField(decimal_places=2, max_digits=14)),
                ("actual_balance", models.DecimalField(decimal_places=2, max_digits=14)),
                ("difference", models.DecimalField(decimal_places=2, max_digits=14)),
                ("reason", models.CharField(max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-reconciliation_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["reconciliation_date", "-created_at"],
                        name="cash_reconcile_date_idx",
                    )
                ],
            },
        ),
    ]
