# Generated by Django 5.2.17 on 2026-08-21 09:48

import uuid

from django.db import migrations, models

import apps.customers.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer_code",
                    models.CharField(
                        default=apps.customers.models.generate_customer_code,
                        editable=False,
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("full_name", models.CharField(db_index=True, max_length=150)),
                ("phone", models.CharField(blank=True, db_index=True, max_length=30)),
                ("whatsapp_number", models.CharField(blank=True, db_index=True, max_length=20)),
                ("whatsapp_consent", models.BooleanField(db_index=True, default=False)),
                ("whatsapp_consent_at", models.DateTimeField(blank=True, null=True)),
                ("address", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "ordering": ["full_name", "customer_code"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "full_name"], name="customer_active_name_idx"
                    ),
                    models.Index(fields=["created_at"], name="customer_created_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("whatsapp_consent", False),
                            models.Q(("whatsapp_number", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="customer_consent_requires_whatsapp",
                    )
                ],
            },
        ),
    ]
